SHOW PARAMETERS FOR SESSION;
ALTER SESSION SET ABORT_DETACHED_QUERY = TRUE;

SHOW PARAMETERS FOR ACCOUNT;
ALTER SESSION SET STATEMENT_TIMEOUT_IN_SECONDS = 3600; -- 1 hour

SHOW PARAMETERS FOR WAREHOUSE;
ALTER WAREHOUSE NEOBANK_WH SET AUTO_SUSPEND = 60;
